### PR TITLE
Fix "Content-Type" header being overriden

### PR DESCRIPTION
**Pull request by bernardkkt**
Moved the "if (typeis(init.Headers)(init.headers))..." block lower to preserve user-defined string for 'Content-Type' header.

### CODE REVIEW

**Comment by maple3142** [comment]
Maybe add an extra test for this?

**Comment by bernardkkt** [comment]
Now I ran into issue with the code, my bad for skipping the test. if I couldn't deliver a test a few days later, please close it. Sorry for wasting your time

**Comment by bernardkkt** [comment]
Close due to invalid fix.

**Comment by bernardkkt** [comment]
Hi @maple3142 , it would be great if you have spare time to glance the commits below. This is the first time I am trying to fix a Nodejs script :smile: not sure if I have added the tests correctly.

- Changes to **xfetch.js** https://github.com/bernardkkt/xfetch-js/commit/0b7764ce598c25eea4b2c52a29c4a8e32c41a4d1
- Changes to **test/index.js** https://github.com/bernardkkt/xfetch-js/commit/16bf14992053e879fd6b5c8bf4bc90e4e9cd7bb9

Thank you.

**Comment by maple3142** [comment]
fixed in e5d2365d7e2aeb5c36a1b7b31b2cc8cefdfa70e0

**Pull request closed without merging**
